/**
 * android — writes everything the Android build needs to be per-client.
 *
 * Two kinds of output:
 *
 *   1. A `productFlavors` block injected into `android/app/build.gradle`
 *      between the marker comments below. The markers are what make this safe:
 *      hand-written Gradle outside them is never touched, so a normal
 *      `./gradlew` edit still works and a re-sync never clobbers it.
 *
 *   2. A flavor source set at `android/app/src/<flavor>/` holding just the two
 *      files that must differ per client on the native side:
 *
 *        values/strings.xml   → @string/app_name (launcher label)
 *        values/colors.xml    → @color/brand_launch_background (cold-start)
 *
 *      Icons come from `scripts/generators/icons.js` into the same source set.
 *
 * ── Source set priority, and why Butru keeps working untouched ──────────────
 * Android merges `src/main` + `src/<flavor>` with the flavor winning. Butru is
 * the fallback for everything not overridden, so a brand-new client that forgets
 * an asset shows Butru's artwork. `assertFlavorResourcesPresent` below turns
 * that silent failure into a loud build error instead.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { ROOT, loadRegistry } = require('../lib/clientRegistry');
const { generateIcons, hasMaster } = require('./icons');

const GRADLE_FILE = path.join(ROOT, 'android', 'app', 'build.gradle');
const FLAGS_BEGIN = '// ── clients:sync:begin flavors ──';
const FLAGS_END = '// ── clients:sync:end flavors ──';
const DEBUGGABLE_BEGIN = '// ── clients:sync:begin debuggableVariants ──';
const DEBUGGABLE_END = '// ── clients:sync:end debuggableVariants ──';

/**
 * Replaces everything between the markers with `body`, writing the markers back
 * itself.
 *
 * The wrapper owns the markers deliberately. When the caller supplied its own
 * copy it was possible to forget the closing one, which silently deleted the
 * marker from build.gradle and made every later sync fail. Now a body can never
 * affect marker integrity.
 *
 * Returns true when the file actually changed.
 */
function replaceBetween(body, begin, end, { check = false } = {}) {
  if (!fs.existsSync(GRADLE_FILE)) {
    throw new Error('[android] android/app/build.gradle not found');
  }
  const current = fs.readFileSync(GRADLE_FILE, 'utf8');

  const startIdx = current.indexOf(begin);
  const endIdx = current.indexOf(end);

  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `[android] build.gradle is missing the sync markers:\n` +
        `    ${begin}\n    ${end}\n` +
        '  Re-apply the Phase 3 patch, or add them yourself.',
    );
  }
  if (endIdx < startIdx) {
    throw new Error(
      '[android] the closing marker comes before the opening one in ' +
        'build.gradle — fix the file by hand.',
    );
  }

  // Anything left inside the block must not itself contain a marker, or the
  // next run would match the wrong pair.
  if (body.includes(begin) || body.includes(end)) {
    throw new Error('[android] generated body must not contain its own markers');
  }

  const next =
    current.slice(0, startIdx) +
    `${begin}\n${body}\n${end}` +
    current.slice(endIdx + end.length);

  if (next === current) return false;
  if (!check) fs.writeFileSync(GRADLE_FILE, next, 'utf8');
  return true;
}

// ── build.gradle productFlavors ──────────────────────────────────────────────

/** Body of the productFlavors block — no markers; replaceBetween adds them. */
function renderFlavorBlock(registry) {
  const blocks = Object.keys(registry.clients).map((id) => {
    const c = registry.clients[id];
    const flavor = id.toLowerCase().replace(/[^a-z0-9]/g, '');
    const isDefault = id === registry.defaultClient;
    const lines = [
      `    // ${c.displayName}${isDefault ? '   (default — keeps the pre-flavour IDs)' : ''}`,
      `    create("${flavor}") {`,
      `        dimension "client"`,
    ];

    // The default client keeps applicationId exactly as it is today, so its Play
    // Store listing, signing identity and update path are untouched.
    if (!isDefault) {
      lines.push(`        applicationId "${c.android.applicationId}"`);
    }

    // versionCode is per client, not global: each tenant's store listing counts
    // up independently. Bump it here when that client's release goes out.
    lines.push(`        versionCode ${c.android.versionCode || 1}`);
    lines.push(`        resValue "string", "build_client", "${id}"`);
    lines.push(`        resValue "string", "client_store_id", "${escapeAndroid(c.api.storeId)}"`);
    lines.push(`        resValue "string", "client_store_slug", "${escapeAndroid(c.api.storeSlug)}"`);
    lines.push('    }');
    return lines.join('\n');
  });

  return [
    '    // Generated by `npm run clients:sync` — edit clients/clients.json instead.',
    '    //',
    '    // `namespace` deliberately stays com.butruproject: MainActivity and',
    '    // MainApplication live in that Kotlin package and AndroidManifest refers to',
    '    // them as ".MainActivity", so only `applicationId` varies per client.',
    '    // Adding a client never means moving a .kt file.',
    '    flavorDimensions "client"',
    '    productFlavors {',
    blocks.join('\n\n'),
    '    }',
  ].join('\n');
}

function writeFlavorBlock(registry) {
  return replaceBetween(renderFlavorBlock(registry), FLAGS_BEGIN, FLAGS_END);
}

/**
 * `debuggableVariants` must name every flavor's debug variant, or Gradle bundles
 * JS into debug builds and Metro / fast refresh silently stops working. Deriving
 * it from the same registry keeps the two blocks from drifting apart.
 */
function renderDebuggableBlock(registry) {
  const variants = [];
  Object.keys(registry.clients).forEach((id) => {
    const flavor = id.toLowerCase().replace(/[^a-z0-9]/g, '');
    variants.push(`        "${flavor}Debug"`, `        "${flavor}DebugOptimized"`);
  });
  return [
    '    // Generated by `npm run clients:sync` — kept in step with productFlavors.',
    '    debuggableVariants = [',
    variants.join(',\n'),
    '    ]',
  ].join('\n');
}

function writeDebuggableBlock(registry) {
  return replaceBetween(
    renderDebuggableBlock(registry),
    DEBUGGABLE_BEGIN,
    DEBUGGABLE_END,
  );
}

// ── flavor source sets ───────────────────────────────────────────────────────

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Escapes a value so it is safe inside a quoted Groovy string literal. */
function escapeAndroid(value) {
  return String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"');
}

function renderStrings(client) {
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by `npm run clients:sync` — do not edit. -->',
    '<resources>',
    '    <!-- Launcher label under the icon. Must match the iOS',
    '         CLIENT_DISPLAY_NAME in ios/Config/Clients/<id>.xcconfig. -->',
    `    <string name="app_name">${escapeXml(client.displayName)}</string>`,
    '</resources>',
    '',
  ].join('\n');
}

function renderColors(client) {
  const light = (client.theme || {}).light || {};
  const bg =
    (client.raw.splash && client.raw.splash.background) ||
    light.primary ||
    '#B12B5B';
  const accent =
    (client.raw.splash && client.raw.splash.accent) ||
    light.secondary ||
    '#FF6B35';
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by `npm run clients:sync` — do not edit. -->',
    '<!--',
    '  Painted behind the app during the cold-start frames, before React Native',
    '  mounts and SplashScreen.tsx can read the storefront theme. It has to be a',
    '  compile-time constant because the launch theme is baked into the binary,',
    '  and it is resolved at install time per tenant.',
    '',
    '  Keep it in step with the client\'s "theme" block in clients.json (or, when',
    '  unset, with src/config/app_config.ts) or the hand-off from the native',
    '  window to the JS splash will visibly jump on a fresh install.',
    '-->',
    '<resources>',
    `    <color name="brand_launch_background">${escapeXml(bg)}</color>`,
    `    <color name="brand_accent">${escapeXml(accent)}</color>`,
    '</resources>',
    '',
  ].join('\n');
}

function writeFlavorSources(client) {
  const values = path.join(
    ROOT, 'android', 'app', 'src', client.flavor, 'res', 'values',
  );
  fs.mkdirSync(values, { recursive: true });

  const strings = path.join(values, 'strings.xml');
  const colors = path.join(values, 'colors.xml');
  fs.writeFileSync(strings, renderStrings(client), 'utf8');
  fs.writeFileSync(colors, renderColors(client), 'utf8');
  return [strings, colors];
}

// ── entry point ──────────────────────────────────────────────────────────────

function generate({ check, log = () => {} }) {
  const { resolveClient } = require('../lib/clientRegistry');
  const registry = loadRegistry();

  // Every client gets its sources, not just the one being built — otherwise
  // switching clients would need two syncs before the build was correct.
  const written = [];
  Object.keys(registry.clients).forEach((id) => {
    const client = resolveClient(id, registry);
    if (check) return;
    written.push(...writeFlavorSources(client));
    if (client.android.icon && hasMaster(client.android.icon)) {
      written.push(...generateIcons(client.android.icon));
    }
  });

  if (!check) {
    const flavorsChanged = writeFlavorBlock(registry);
    const debugChanged = writeDebuggableBlock(registry);
    if (flavorsChanged || debugChanged) {
      log('  gradle   → android/app/build.gradle (productFlavors, debuggableVariants)');
    }
  }

  return written;
}

module.exports = {
  generate,
  renderFlavorBlock,
  renderDebuggableBlock,
  FLAGS_BEGIN,
  FLAGS_END,
  DEBUGGABLE_BEGIN,
  DEBUGGABLE_END,
};
