/**
 * icons — turns one committed 1024x1024 master per client into every size the
 * two platforms need.
 *
 * ── Why a single master ─────────────────────────────────────────────────────
 * Every icon set for a platform has 15 (Android) to 20 (iOS) files at fixed
 * pixel sizes. Committing 50 clients x 35 files = 1,700 near-duplicate PNGs that
 * nobody can meaningfully review or diff. Instead we commit ONE master per
 * client at `clients/icons/<client>/icon.png` and derive the rest.
 *
 * The derived files are build output, so they are git-ignored and regenerated by
 * `npm run clients:sync` — which every `npm run android:*` / `ios:*` runs first.
 *
 * ── Why Butru is untouched ──────────────────────────────────────────────────
 * `clients.json` sets `"icon": null` for a client to mean "use the icons already
 * in the repo". Butru is `null`, so its artwork is bit-for-bit what shipped
 * before flavours existed. A client with `"icon": "<id>"` gets a generated set.
 *
 * ── No image-library dependency ──────────────────────────────────────────────
 * `sips` ships with macOS and does the resizing. Only the *circular* Android
 * round icon needs a mask, which sips cannot do — that one falls back to PIL
 * when present and to a plain copy when not.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { ROOT } = require('../lib/clientRegistry');

// Legacy launcher icon edge length, in pixels, per density bucket.
const ANDROID_MIPMAPS = {
  mdpi: 48,
  hdpi: 72,
  xhdpi: 96,
  xxhdpi: 144,
  xxxhdpi: 192,
};

// Mirrors the exact set in ios/butruProject/Images.xcassets/AppIcon.appiconset
// so a generated set validates on the App Store identically to the existing one.
const IOS_ICONS = [
  ['Icon-App-20x20@1x.png', 20],
  ['Icon-App-20x20@2x.png', 40],
  ['Icon-App-20x20@3x.png', 60],
  ['Icon-App-29x29@1x.png', 29],
  ['Icon-App-29x29@2x.png', 58],
  ['Icon-App-29x29@3x.png', 87],
  ['Icon-App-40x40@1x.png', 40],
  ['Icon-App-40x40@2x.png', 80],
  ['Icon-App-40x40@3x.png', 120],
  ['Icon-App-60x60@2x.png', 120],
  ['Icon-App-60x60@3x.png', 180],
  ['Icon-App-76x76@1x.png', 76],
  ['Icon-App-76x76@2x.png', 152],
  ['Icon-App-83.5x83.5@2x.png', 167],
  ['ItunesArtwork@2x.png', 1024],
];

const IOS_CONTENTS_JSON = {
  images: [
    { idiom: 'iphone', size: '20x20', scale: '1x', filename: 'Icon-App-20x20@1x.png' },
    { idiom: 'iphone', size: '20x20', scale: '2x', filename: 'Icon-App-20x20@2x.png' },
    { idiom: 'iphone', size: '20x20', scale: '3x', filename: 'Icon-App-20x20@3x.png' },
    { idiom: 'iphone', size: '29x29', scale: '1x', filename: 'Icon-App-29x29@1x.png' },
    { idiom: 'iphone', size: '29x29', scale: '2x', filename: 'Icon-App-29x29@2x.png' },
    { idiom: 'iphone', size: '29x29', scale: '3x', filename: 'Icon-App-29x29@3x.png' },
    { idiom: 'iphone', size: '40x40', scale: '2x', filename: 'Icon-App-40x40@2x.png' },
    { idiom: 'iphone', size: '40x40', scale: '3x', filename: 'Icon-App-40x40@3x.png' },
    { idiom: 'iphone', size: '60x60', scale: '2x', filename: 'Icon-App-60x60@2x.png' },
    { idiom: 'iphone', size: '60x60', scale: '3x', filename: 'Icon-App-60x60@3x.png' },
    { idiom: 'iphone', size: '76x76', scale: '2x', filename: 'Icon-App-76x76@2x.png' },
    { idiom: 'ipad', size: '20x20', scale: '1x', filename: 'Icon-App-20x20@1x.png' },
    { idiom: 'ipad', size: '20x20', scale: '2x', filename: 'Icon-App-20x20@2x.png' },
    { idiom: 'ipad', size: '29x29', scale: '1x', filename: 'Icon-App-29x29@1x.png' },
    { idiom: 'ipad', size: '29x29', scale: '2x', filename: 'Icon-App-29x29@2x.png' },
    { idiom: 'ipad', size: '40x40', scale: '1x', filename: 'Icon-App-40x40@1x.png' },
    { idiom: 'ipad', size: '40x40', scale: '2x', filename: 'Icon-App-40x40@2x.png' },
    { idiom: 'ipad', size: '76x76', scale: '1x', filename: 'Icon-App-76x76@1x.png' },
    { idiom: 'ipad', size: '76x76', scale: '2x', filename: 'Icon-App-76x76@2x.png' },
    { idiom: 'ipad', size: '83.5x83.5', scale: '2x', filename: 'Icon-App-83.5x83.5@2x.png' },
    { idiom: 'ios-marketing', size: '1024x1024', scale: '1x', filename: 'ItunesArtwork@2x.png' },
  ],
  info: { version: 1, author: 'clients:sync' },
};

const sipsAvailable = (() => {
  try {
    execFileSync('sips', ['--help'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
})();

function resize(master, outPath, size) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  execFileSync('sips', [
    '-z', String(size), String(size),
    master,
    '--out', outPath,
  ], { stdio: 'ignore' });
  return outPath;
}

/**
 * Circular variant for `ic_launcher_round`. sips cannot mask, so this is the
 * one step that needs PIL; without it we fall back to the square image, which
 * renders slightly square on launchers that honour the round variant.
 *
 * `size` must be the real density size, not a master size: Android picks a
 * mipmap by bucket and scales, so a 512px file dropped into mipmap-xxxhdpi is
 * not "downscaled for density", it is a ~1 MB APK bloat that then gets resampled
 * to 320px and looks soft.
 */
function roundify(srcPath, outPath, size) {
  const script = `
import sys
from PIL import Image, ImageDraw
src, dst, px = sys.argv[1], sys.argv[2], int(sys.argv[3])
im = Image.open(src).convert("RGBA").resize((px, px), Image.LANCZOS)
# 4x supersampled mask, then downsample: a direct ellipse edge at 48px shows
# obvious stair-stepping once Android scales the icon up slightly.
mask = Image.new("L", (px * 4, px * 4), 0)
ImageDraw.Draw(mask).ellipse((0, 0, px * 4 - 1, px * 4 - 1), fill=255)
mask = mask.resize((px, px), Image.LANCZOS)
im.putalpha(mask)
im.save(dst, "PNG", optimize=True)
`;
  try {
    execFileSync('python3', ['-c', script, srcPath, outPath, String(size)], {
      stdio: 'ignore',
    });
    return true;
  } catch {
    // No PIL. A square icon is a far better outcome than a build failure.
    fs.copyFileSync(srcPath, outPath);
    return false;
  }
}

/** iOS asset-catalog folder name for a client, e.g. `clienta` → `AppIcon_ClientA`. */
function iosAssetName(clientId) {
  const suffix = clientId.charAt(0).toUpperCase() + clientId.slice(1);
  return `AppIcon_${suffix}`;
}

/** True when this client has a master icon to derive from. */
function hasMaster(clientId) {
  return (
    !!clientId &&
    fs.existsSync(path.join(ROOT, 'clients', 'icons', clientId, 'icon.png'))
  );
}

/**
 * Generates one client's icons for both platforms.
 *
 * @returns {{ android: string[], ios: string[] }}
 */
function generateIcons(clientId) {
  const master = path.join(ROOT, 'clients', 'icons', clientId, 'icon.png');
  if (!fs.existsSync(master)) {
    throw new Error(
      `[icons] Master icon missing for "${clientId}".\n` +
        `  expected: clients/icons/${clientId}/icon.png (1024x1024 PNG)\n` +
        `  or set "icon": null in clients.json to reuse the existing artwork.`,
    );
  }
  if (!sipsAvailable) {
    throw new Error(
      '[icons] `sips` not found. It ships with macOS — run this on a Mac, or ' +
        'pre-generate the icons in CI.',
    );
  }

  const written = [];

  // ── Android: one mipmap folder per density, in the flavor source set ──────
  Object.entries(ANDROID_MIPMAPS).forEach(([density, size]) => {
    const dir = path.join(
      ROOT, 'android', 'app', 'src', clientId, 'res', `mipmap-${density}`,
    );
    const launcher = resize(master, path.join(dir, 'ic_launcher.png'), size);
    written.push(launcher);

    const roundSrc = path.join(dir, '.round-src.png');
    resize(master, roundSrc, size);
    const roundOut = path.join(dir, 'ic_launcher_round.png');
    roundify(roundSrc, roundOut, size);
    fs.unlinkSync(roundSrc);
    written.push(roundOut);
  });

  // ── iOS: a full appiconset inside the EXISTING Images.xcassets ────────────
  // Dropping it inside a catalog already referenced by the Xcode project means
  // Xcode picks it up with no .pbxproj edit at all.
  const setDir = path.join(
    ROOT, 'ios', 'butruProject', 'Images.xcassets', iosAssetName(clientId) + '.appiconset',
  );
  fs.mkdirSync(setDir, { recursive: true });
  IOS_ICONS.forEach(([filename, size]) => {
    written.push(resize(master, path.join(setDir, filename), size));
  });
  const contents = path.join(setDir, 'Contents.json');
  fs.writeFileSync(contents, `${JSON.stringify(IOS_CONTENTS_JSON, null, 2)}\n`, 'utf8');
  written.push(contents);

  return written;
}

module.exports = {
  generateIcons,
  hasMaster,
  iosAssetName,
  ANDROID_MIPMAPS,
  IOS_ICONS,
};
