/**
 * ios — writes the xcconfig layer that makes an iOS build per-client.
 *
 * ── Why xcconfig and not 50 schemes ─────────────────────────────────────────
 * One Xcode scheme per client means 50 scheme files and a pbxproj that Xcode
 * progressively refuses to open quickly. Instead there is exactly one scheme
 * (`butruProject`) and two build configurations (Debug / Release), and the
 * client-specific values arrive through an `.xcconfig` include chain:
 *
 *   Config/Shared.xcconfig          ← committed, hand-editable, RN defaults
 *     └─ Config/Client.xcconfig      ← generated, git-ignored  (one per client)
 *          └─ Config/Clients/<id>.xcconfig  ← committed, one per client
 *
 * `Client.xcconfig` is a one-line `#include` of the selected client's file, so
 * `npm run ios -- --client clienta` switches everything by rewriting two lines.
 * Nothing in the .pbxproj is touched after initial setup, and any number of
 * clients can be archived from CI in parallel.
 *
 * ── What each client gets ───────────────────────────────────────────────────
 *   PRODUCT_BUNDLE_IDENTIFIER         com.company.clienta
 *   PRODUCT_NAME                      ClientA
 *   ASSETCATALOG_COMPILER_APPICON_NAME AppIcon_ClientA
 *   CLIENT_ENV_FILE                   .env.clienta        → babel picks it up
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { ROOT, loadRegistry, resolveClient, metroPort, rel } = require('../lib/clientRegistry');
const { generateIcons, hasMaster, iosAssetName } = require('./icons');

const CONFIG_DIR = path.join(ROOT, 'ios', 'Config');
const CLIENTS_DIR = path.join(CONFIG_DIR, 'Clients');

// ── ios/Config/Clients/<id>.xcconfig  (committed, one per client) ────────────

/**
 * An xcconfig is NOT a C preprocessor file, despite `#include` looking like one.
 * `#` starts a directive, so a `# comment` line becomes
 *
 *     error: unsupported preprocessor directive 'Replaces'
 *
 * and fails the build with a wall of errors that says nothing about the real
 * mistake. Only `//` and `/* *\/` are comments here. Checking before write turns
 * a 40-line mystery into one clear line.
 */
function assertValidXcconfig(text, label) {
  const bad = text
    .split('\n')
    .map((line, i) => ({ line, n: i + 1 }))
    .filter(({ line }) => /^\s*#/.test(line) && !/^\s*#include/.test(line));

  if (bad.length > 0) {
    throw new Error(
      `[ios] ${label} uses '#' for comments, which xcconfig treats as a ` +
        `preprocessor directive. Use '//' instead. Offending lines: ` +
        bad.map((b) => b.n).join(', '),
    );
  }
}

function renderClientXcconfig(client, registry) {
  const isDefault = client.id === registry.defaultClient;
  const appIcon = client.ios.icon ? iosAssetName(client.ios.icon) : 'AppIcon';
  const version = client.ios.version || '1.0';
  const team = client.ios.teamId || '';
  const port = metroPort(client.id, registry);

  // Built outside the template literal — a nested one here confuses the parser
  // and reads badly besides.
  const signing = team
    ? [
        '',
        '// ── Signing ───────────────────────────────────────────────────────────────',
        '// Each client can sit under a different Apple Developer account.',
        `DEVELOPMENT_TEAM = ${team}`,
      ].join('\n')
    : '';

  const defaultNote = isDefault
    ? '\n// (default client — matches what this app shipped with before flavours)'
    : '';

  return [
    '// ─────────────────────────────────────────────────────────────────────────',
    `// Client: ${client.displayName}`,
    '//',
    '// Generated by `npm run clients:sync` from clients/clients.json.',
    '// Committed on purpose — this is the permanent record of this client\'s store',
    '// identity. The per-build wrapper that selects it is Config/Client.xcconfig.',
    '//',
    '// Note: PRODUCT_NAME is deliberately NOT set here. The app keeps building as',
    '// butruProject.app; what the user sees on the home screen comes from',
    "// CLIENT_DISPLAY_NAME via Info.plist's CFBundleDisplayName. Changing",
    '// PRODUCT_NAME would rename the executable and risk breaking the React Native',
    '// bundle script phase for no user-visible gain.',
    '// ─────────────────────────────────────────────────────────────────────────',
    '',
    '// ── Store identity ───────────────────────────────────────────────────────',
    `PRODUCT_BUNDLE_IDENTIFIER = ${client.ios.bundleId}`,
    `MARKETING_VERSION = ${version}`,
    `CURRENT_PROJECT_VERSION = 1${defaultNote}`,
    '',
    '// ── Per-client Info.plist ──────────────────────────────────────────────',
    '// One plist per client, so a client can carry its own permissions, URL',
    '// schemes or background modes without touching anyone else\'s build.',
    '// Shared.xcconfig holds the default client\'s path as a fallback.',
    `INFOPLIST_FILE = butruProject/Clients/${client.id}/Info.plist`,
    '',
    '// ── Home-screen label ───────────────────────────────────────────────────',
    '// Replaces the hardcoded "Butru" that used to sit in Info.plist.',
    `CLIENT_DISPLAY_NAME = ${client.displayName}`,
    '',
    '// ── Native store identity ────────────────────────────────────────────────',
    '// Info.plist substitutes these into ClientStoreId / ClientStoreSlug, and',
    '// AppDelegate hands them to JS at runtime. They are baked into the binary',
    '// (not the bundle), so a client app keeps its own store identity even if',
    '// another client\'s Metro is serving 8081.',
    `CLIENT_STORE_ID = ${client.api.storeId}`,
    `CLIENT_STORE_SLUG = ${client.api.storeSlug}`,
    '',
    '// ── App icon ────────────────────────────────────────────────────────────',
    '// Points at an appiconset inside the existing Images.xcassets, so no new',
    '// resource has to be added to the Xcode project.',
    `ASSETCATALOG_COMPILER_APPICON_NAME = ${appIcon}`,
    signing,
    '',
    '// ── Build-time environment ──────────────────────────────────────────────',
    '// Read by babel.config.js so the JS bundle is built against this client API.',
    '// Xcode exports build settings into the environment of every Run Script phase,',
    '// which is where the React Native bundle step picks this up. If that ever stops',
    "// working, babel reads the client id from clients/active.json instead.",
    `CLIENT_ID = ${client.id}`,
    '',
    '// ── Dev packager port ──────────────────────────────────────────────────',
    '// Info.plist substitutes $(RCT_METRO_PORT) into MetroPort, and AppDelegate',
    '// feeds that to RCTBundleURLProvider. Without it the app asks for 8081',
    "// (React's compiled-in default), so a client on any other port fails with",
    '// "No script URL provided" even though its bundler is running fine.',
    '// Must match the port `npm run start -- --client <id>` uses.',
    `RCT_METRO_PORT = ${port}`,
    '',
  ].join('\n');
}

// ── ios/Config/Client.xcconfig  (generated, git-ignored) ─────────────────────

/**
 * The only per-build file. Selecting a different client is a two-line change
 * here, which is what keeps 50 clients from needing 50 schemes.
 */
function renderActiveXcconfig(resolved) {
  return `// AUTO-GENERATED by \`npm run clients:sync\` — do not edit, do not commit.
// Regenerate: npm run clients:sync -- --client ${resolved.id}
#include "Clients/${resolved.id}.xcconfig"

// Which generated env file babel.config.js should inline. The file holds this
// client's single API base URL — there is no environment axis.
CLIENT_ENV_FILE = .env.${resolved.id}
`;
}

// ── entry point ──────────────────────────────────────────────────────────────

function generate({ resolved, check, log = () => {} }) {
  const registry = loadRegistry();
  fs.mkdirSync(CLIENTS_DIR, { recursive: true });

  const written = [];

  Object.keys(registry.clients).forEach((id) => {
    const client = resolveClient(id, registry);
    const file = path.join(CLIENTS_DIR, `${id}.xcconfig`);

    if (client.ios.icon && hasMaster(client.ios.icon) && !check) {
      written.push(...generateIcons(client.ios.icon));
    }

    if (!check) {
      const rendered = renderClientXcconfig(client, registry);
      assertValidXcconfig(rendered, `${id}.xcconfig`);
      fs.writeFileSync(file, rendered, 'utf8');
      written.push(file);
    }
  });

  if (!check) {
    const active = path.join(CONFIG_DIR, 'Client.xcconfig');
    const rendered = renderActiveXcconfig(resolved);
    assertValidXcconfig(rendered, 'Client.xcconfig');
    fs.writeFileSync(active, rendered, 'utf8');
    written.push(active);
    log(`  xcconfig → ${rel(active)} → ${resolved.id}.xcconfig`);
  }

  return written;
}

module.exports = {
  generate,
  renderClientXcconfig,
  renderActiveXcconfig,
  iosAssetName,
};
